spring:
  profiles: lz
  datasource:
    #mysql8驱动
    #driver-class-name: com.mysql.cj.jdbc.Driver

    #mysql5驱动
    driver-class-name: com.mysql.jdbc.Driver
    url:
    username:
    password:


#  redis:
#    database: 0
#    host:
#    port:
#    password:
#    lettuce:
#      shutdown-timeout: 0ms